---
classification: gem
production: {}
performance_monitoring: []
error_monitoring: []
continuous_integration: []
bug_tracking: []
documentation: []
deployment: []
languages:
  - name: Ruby
    version: 3.0.6
frameworks: []
logging: []
infrastructure:
  application:
    name: pipe-ruby
    image: ruby
    imageTag: 3.0-slim
    startcmd: "bundle exec rspec"
    vault-path: dev/applications/data/pipe-ruby/dotenv
